import {  Lato } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const leto = Lato({
   variable:"--font-lato-sans",
   weight: ['400', '700'], 
   subsets:["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    data-theme="light"
      lang="en"
      className={`${leto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <Navbar />
        
        {children}

        <Footer/>
      </body>
    </html>
  );
}
